apiVersion: apps/v1
kind: Deployment
metadata:
  name: casino-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casino-postgres
  template:
    metadata:
      labels:
        app: casino-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: casino-secrets
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: casino-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: casino-secrets
                  key: DB_NAME
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: casino-postgres
spec:
  type: ClusterIP
  selector:
    app: casino-postgres
  ports:
    - port: 5432
      targetPort: 5432